#!/usr/bin/env bash

function _run_tests() {
  _configure_global_variables
  _source_required_modules
  bst_release__concatenate_sources_in_release_file
  source "$(bst_release__get_released_artifact_file)"
  source "${TESTS_DIR}/shebang_unit" "$@" "${TESTS_DIR}"
}

function _source_required_modules() {
	source "${SOURCES_DIR}/release.sh"
}

function _configure_global_variables() {
  local root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"
  SOURCES_DIR="${root_dir}/sources"
  TESTS_DIR="${root_dir}/tests"
}

_run_tests "$@"
