#!/usr/bin/env bash

function _run_tests() {
  _configure_global_variables
  _create_tmp_dir
  _source_required_modules
  bst_release__concatenate_sources_in_release_file
  source "$(bst_release__get_released_artifact_file)"
  source "${TESTS_DIR}/shebang_unit" "$@" "${TESTS_DIR}"
  _remove_tmp_dir
}

function _create_tmp_dir() {
  mkdir -p "${TMP_DIR}"
}

function _remove_tmp_dir() {
  [[ "${TMP_DIR}" = /tmp/* ]] && rm -rf "${TMP_DIR}"
}

function _source_required_modules() {
	source "${SOURCES_DIR}/release.sh"
	source "${TESTS_DIR}/test_helper.sh"
}

function _configure_global_variables() {
  local root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"
  SOURCES_DIR="${root_dir}/sources"
  TESTS_DIR="${root_dir}/tests"
  TMP_DIR="/tmp/${RANDOM}"
  BST__CONFIG_DIR="${TMP_DIR}"
}

_run_tests "$@"
