#!/usr/bin/env bash

# Copyright (C) 2015, Arpinum
#
# Beastmaster is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Beastmaster is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# Beastmaster. If not, see http://www.gnu.org/licenses/lgpl.html.

# Beastmaster all in one source file


function bst_config__load() {
  BST__CONFIG_DIR="${HOME}/.bst"
  bst_config__ensure_config_file_exists
}

function bst_config__config_file() {
  system__print "${BST__CONFIG_DIR}/config"
}

function bst_config__ensure_config_file_exists() {
  mkdir -p "${BST__CONFIG_DIR}"
  touch "$(bst_config__config_file)"
}


function system__print_line() {
  system__print "$1"
  system__print_new_line
}

function system__print() {
  printf "%s" "$1"
}

function system__print_new_line() {
  printf "\n"
}


function command__help_triggered() {
  _command__print_usage
  exit 0
}

function command__illegal_option_parsed() {
  local option="${1%=*}"
  option="${option#-}"
  option="${option#-}"
  system__print_line "$(_command__name): illegal option -- ${option}"
  system__print_new_line
  _command__print_usage
  exit 1
}

function command__illegal_command_parsed() {
  system__print_line "$(_command__name): illegal command -- $1"
  system__print_new_line
  _command__print_usage
  exit 1
}

function _command__print_usage() {
  system__print_line "$(_bst_${BST__CURRENT_COMMAND}_command__usage)"
}

function _command__name() {
  [[ "${BST__CURRENT_COMMAND}" == "default" ]] \
    && system__print "bst" \
    || system__print "bst ${BST__CURRENT_COMMAND}"
}


function bst_pet__name_from_line() {
  _bst_pet__first_token "$1"
}

function bst_pet__directory_from_line() {
  local without_name="$(_bst_pet__without_first_token "$1")"
  _bst_pet__first_token "${without_name}"
}

function bst_pet__tags_from_line() {
  local without_name="$(_bst_pet__without_first_token "$1")"
  local only_tags="$(_bst_pet__without_first_token "${without_name}")"
  while [[ -n "${only_tags}" ]]; do
    _bst_pet__first_token "${only_tags}"
    system__print_new_line
    only_tags="$(_bst_pet__without_first_token "${only_tags}")"
  done
}

function _bst_pet__first_token() {
  system__print "${1%%:*}"
}

function _bst_pet__without_first_token() {
  [[ "$1" == *:* ]] && system__print "${1#*:}"
}


function bst_config_command__run() {
  BST__CURRENT_COMMAND="config"
  "${EDITOR}" "$(bst_config__config_file)"
}


function bst_free_command__run() {
  system__print_line "free with $@"
}


function bst_list_command__run() {
  BST__CURRENT_COMMAND="list"
  (( $# == 0 )) && _bst_list_command__list_pets
  _bst_list_command__parse_arguments "$@"
}

function _bst_list_command__parse_arguments() {
  local argument
  for argument in "$@"; do
    case "${argument}" in
      -h|--help)
      command__help_triggered
      ;;
      -*|--*)
      command__illegal_option_parsed "${argument}"
      ;;
      *)
      command__illegal_command_parsed "${argument}"
      ;;
    esac
  done
}

function _bst_list_command__usage() {
  system__print "\
Usage: bst list

Print the project list."
}

function _bst_list_command__list_pets() {
  local line
  while read line; do
    local name="$(bst_pet__name_from_line "${line}")"
    local dir="$(bst_pet__directory_from_line "${line}")"
    local tags="$(_bst_list_comand__tags_from_line "${line}")"
    system__print_line "${name} at ${dir}${tags}"
  done < "$(bst_config__config_file)"
}

function _bst_list_comand__tags_from_line() {
  local tags="$(bst_pet__tags_from_line "$1")"
  for tag in ${tags[@]}; do
    system__print " #${tag}"
  done
}


function bst_order_command__run() {
  system__print_line "order with $@"
}


function bst_tame_command__run() {
  system__print_line "tame with $@"
}


function bst_program__run() {
  bst_config__load
  BST__CURRENT_COMMAND="default"
  (( $# == 0 )) && _bst_program__print_usage_and_exit_normally
  _bst_program__parse_arguments "$@"
}

function _bst_program__parse_arguments() {
  local argument
  for argument in "$@"; do
    case "${argument}" in
      -h|--help)
      command__help_triggered
      ;;
      -*|--*)
      command__illegal_option_parsed "${argument}"
      ;;
      *)
      shift 1
      _bst_program__run_command "${argument}" "$@"
    esac
  done
}

function _bst_program__run_command() {
  local command="$1"
  shift 1
  local command_function="bst_${command}_command__run"
  type "${command_function}" > /dev/null 2>&1 || command__illegal_command_parsed "${command}"
  ${command_function} "$@"
  exit 0
}

function _bst_default_command__usage() {
  system__print "\
Usage: bst <command> [arg...]

A Bash tool which can run any command in your favorite projects.

Options:
  -h, --help  Print usage

Commands:
  config  Edit the configuration
  free    Remove a project from the project list
  list    Print the project list
  order   Execute a command in the project directory
  tame    Add a project to the project list

Run 'bst <command> --help' for more information on a command."
}


[[ "$0" == "${BASH_SOURCE[0]}" ]] && bst_program__run "$@" || true